export const SENDBIRD_USER_INFO = {
  appId: '9DA1B1F4-0BE6-4DA8-82C5-2E81DAB56F23',
  userId: 'SendBird',
  nickname: 'SendBird',
};

export const KEY_ENTER = 'Enter';

export const UNIDIRECTIONAL_MESSAGE_FETCH_LIMIT = 37;

export const BIDIRECTIONAL_MESSAGE_FETCH_LIMIT = UNIDIRECTIONAL_MESSAGE_FETCH_LIMIT * 2;
