name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - added-open-channel-pinned-message  # 또는 원하는 브랜치 이름

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # 또는 프로젝트에 맞는 Node.js 버전

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false  # ESLint 에러 무시
          PUBLIC_URL: https://sendbird.github.io/sendbird-chat-sample-react

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          